language: php

php:
  - 5.4
  - 5.5

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql

before_install:
    - mysql -u root < resources/archive_table.sql
    - mysql -u root < resources/database_schema.sql
    - mysql -u root < resources/insert_data.sql

