language: php

php:
  - 5.4
  - 5.5


before_install:
  - mysql -u root -e 'select version();'
  - mysql -u root < resources/archive_table.sql
  - mysql -u root < resources/database_schema.sql
  - mysql -u root < resources/database_triggers.sql
  - mysql -u root < resources/insert_data.sql
