language: php

php:
  - 5.4
  - 5.5
  - nightly

script: phpunit UnitTest test/CanaryTest.php

env:
  - DB=mysql

before_install:
  - mysql < resources/database_schema.sql
  - mysql < resources/insert_data.sql