language: php

php:
  - 5.4
  - 5.5
  - 5.6

script: phpunit UnitTest test/CanaryTest.php
script: phpunit UnitTest test/GameTest.php

env:
  - DB=mysql

before_install:
  - mysql < resources/archive_table.sql
  - mysql < resources/database_schema.sql
  - mysql < resources/insert_data.sql