language: php

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

php:
  - 5.4
  - 5.5

script: phpunit UnitTest test/CanaryTest.php

env:
  - DB=mysql

before_install:
  - mysql < resources/archive_table.sql
  - mysql < resources/database_schema.sql
  - mysql < resources/database_triggers.sql
  - mysql < resources/insert_data.sql
